#!/data/data/com.termux/files/usr/bin/bash
# KOG authfix v2 - enforce API-key auth on the exposed llama-server
set -u
HOST="llm.agentzein.dev"
PORT=11435
KEYF="$HOME/.llm_api_key"
SL="$HOME/models/start-llama.sh"
LOG="$HOME/llm_authfix_v2.log"
: > "$LOG"
say() { printf '%s\n' "$*" | tee -a "$LOG"; }

say "AUTHFIX-V2-START"
say "DATE=$(date '+%Y-%m-%d %H:%M')"

# 1. file state
say "[1] flag_in_file=$(grep -c -- '--api-key-file' \"$SL\" 2>/dev/null || echo 0)"
grep -o -- '-c 2048[^>]*' "$SL" 2>/dev/null | head -1 | sed 's/^/    /' | tee -a "$LOG"

# 2. running process state
say "[2] running_has_flag=$(pgrep -af llama-server 2>/dev/null | grep -c -- '--api-key-file' || echo 0)"

# 3. key file (value never printed)
if [ -s "$KEYF" ]; then
  say "[3] KEY=EXISTS bytes=$(wc -c < "$KEYF")"
else
  K=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 48)
  ( umask 077; printf '%s' "$K" > "$KEYF" )
  chmod 600 "$KEYF"
  say "[3] KEY=GENERATED bytes=$(wc -c < "$KEYF")"
fi

# 4. ensure flag present in the start script
FC=$(grep -c -- '--api-key-file' "$SL" 2>/dev/null || echo 0)
if [ "$FC" -ge 1 ] 2>/dev/null; then
  say "[4] FILE_PATCH=ALREADY_PRESENT"
else
  cp -p "$SL" "$SL.bak_authfix_v2"
  N=$(grep -c -- '-c 2048 ' "$SL" 2>/dev/null || echo 0)
  say "[4] anchor_matches=$N"
  if [ "$N" = "1" ]; then
    sed -i 's|-c 2048 |-c 2048 --api-key-file "$HOME/.llm_api_key" |' "$SL"
    say "[4] FILE_PATCH=$(grep -c -- '--api-key-file' "$SL" 2>/dev/null || echo 0)"
  else
    say "[4] FILE_PATCH=SKIPPED_anchor_not_unique"
  fi
fi

# 5. restart and prove locally
pkill -f 'llama-server' 2>/dev/null
sleep 3
setsid nohup bash "$SL" > "$HOME/models/start_out.log" 2>&1 < /dev/null &
say "[5] restarted"
H=000
for i in $(seq 1 20); do
  sleep 5
  H=$(curl -s -m 4 -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/health" 2>/dev/null || true)
  say "[5] wait $i health=${H:-000}"
  [ "${H:-}" = "200" ] && break
done
say "[5] running_has_flag_after=$(pgrep -af llama-server 2>/dev/null | grep -c -- '--api-key-file' || echo 0)"

KEY=$(cat "$KEYF")
NA=$(curl -s -m 6 -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/v1/models" 2>/dev/null || true)
AU=$(curl -s -m 8 -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $KEY" "http://127.0.0.1:$PORT/v1/models" 2>/dev/null || true)
say "[5] LOCAL_NOAUTH=${NA:-000} want_401"
say "[5] LOCAL_WITHAUTH=${AU:-000} want_200"

# 6. prove publicly
PN=$(curl -s -m 25 -o /dev/null -w '%{http_code}' "https://$HOST/v1/models" 2>/dev/null || true)
PW=$(curl -s -m 25 -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $KEY" "https://$HOST/v1/models" 2>/dev/null || true)
say "[6] PUBLIC_NOAUTH=${PN:-000} want_401"
say "[6] PUBLIC_WITHAUTH=${PW:-000} want_200"

say "--- SUMMARY ---"
say "KEY_FILE=$KEYF  (view with: cat $KEYF)"
if [ "${PN:-}" = "200" ]; then say "WARNING=STILL_OPEN_TO_INTERNET"; fi
if [ "${PW:-}" = "200" ] && [ "${PN:-}" = "401" ]; then say "RESULT=SECURED"; fi
say "AUTHFIX-V2-END"
